version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq.aspnetcore.publisher:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "EventBus:Host=amqp://guest:guest@rabbitmq:5672"
    restart: always
    ports:
      - "7000:8080"
    depends_on:
      - rabbitmq

  rabbitmq.aspnetcore.subscribers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "EventBus:Host=amqp://guest:guest@rabbitmq:5672"
    restart: always
    ports:
      - "7001:8080"
    depends_on:
      - rabbitmq
